parameters:
  sonar_token: ''

jobs:
- job: Sonar_SAST_Scan_Job
  container: maven:3.8.1-openjdk-17-slim
  steps:
  - script: |
      mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=azuredevopsdevsecopsoorgjou -Dsonar.projectKey=azuredevopsdevsecopsoorgjou -Dsonar.token=$(sonar_token)
    displayName: "Integrate SAST using Sonarcloud to populate code coverage" 
